set -p EXTRA_CMAKE_ARGUMENTS "-DCMAKE_C_COMPILER_LAUNCHER=sccache"
set -p EXTRA_CMAKE_ARGUMENTS "-DCMAKE_CXX_COMPILER_LAUNCHER=sccache"

set -g BUILD_KITS_DISPLAY (string match -v sccache $BUILD_KITS_DISPLAY) || true
