set EXTRA_CMAKE_ARGUMENTS (string match -v -- "-DBUILD_SHARED_LIBS=OFF" $EXTRA_CMAKE_ARGUMENTS)
set EXTRA_CMAKE_ARGUMENTS (string match -v -- "-DBUILD_SHARED_LIBS=ON" $EXTRA_CMAKE_ARGUMENTS)

set -g BUILD_KITS_DISPLAY (string match -v -- static $BUILD_KITS_DISPLAY)
set -g BUILD_KITS_DISPLAY (string match -v -- shared $BUILD_KITS_DISPLAY)

set -ag EXTRA_CMAKE_ARGUMENTS -DBUILD_SHARED_LIBS=ON

# Implicit shared
# set -ag BUILD_KITS_DISPLAY shared

exit 0
